-- German
LANG.AddToLanguage("Deutsch", "totem_already_placed", "Du hast schon ein Totem platziert!")
LANG.AddToLanguage("Deutsch", "totem_place_ground_needed", "Du musst beim Plazieren deines Totems auf dem Boden stehen!")
LANG.AddToLanguage("Deutsch", "totem_placed", "Dein Totem wurde erfolgreich platziert!")
LANG.AddToLanguage("Deutsch", "totem_picked_up", "Du hast dein Totem erfolgreich aufgehoben!")
LANG.AddToLanguage("Deutsch", "totem_destroyed", "Ein Totem wurde zerstört!")
LANG.AddToLanguage("Deutsch", "totem_slow", "Du bist nun deutlich langsamer, weil du kein Totem platziert hast!")
LANG.AddToLanguage("Deutsch", "totem_already_picked_up", "Du kannst dein Totem nur {num} mal aufheben!")
LANG.AddToLanguage("Deutsch", "totem_already_no_pickup", "Du hast dein Totem nicht aufheben!")
LANG.AddToLanguage("Deutsch", "totem_all_destroyed", "Alle Totems wurden zerstört!")
LANG.AddToLanguage("Deutsch", "totem_auto_desc", "Soll das Totem automatisch plaziert werden?")
LANG.AddToLanguage("Deutsch", "totem_other_terrorist", "Dies ist das Totem eines anderen Spielers")
LANG.AddToLanguage("Deutsch", "totem_own_totem", "Dies ist dein Totem")
LANG.AddToLanguage("Deutsch", "totem_teammate_totem", "Das ist das Totem eins Teamkollegen")
LANG.AddToLanguage("Deutsch", "totem_destroy_totem", "Zerstöre dieses Totem mit deinem Messer!")

-- English
LANG.AddToLanguage("English", "totem_already_placed", "You already placed a Totem!")
LANG.AddToLanguage("English", "totem_place_ground_needed", "You need to be grounded to place a Totem!")
LANG.AddToLanguage("English", "totem_placed", "Totem placed successfully!")
LANG.AddToLanguage("English", "totem_picked_up", "You picked up your Totem!")
LANG.AddToLanguage("English", "totem_destroyed", "A Totem was destroyed!")
LANG.AddToLanguage("English", "totem_slow", "You are now noticably slower, due to your Totem being destroyed!")
LANG.AddToLanguage("English", "totem_already_picked_up", "You can pickup your Totem only {num} time(s)!")
LANG.AddToLanguage("English", "totem_already_no_pickup", "You can't pickup your Totem!")
LANG.AddToLanguage("English", "totem_all_destroyed", "All Totems have been destroyed!")
LANG.AddToLanguage("English", "totem_auto_desc", "Should the system try to place the Totem automaticially at round start?")
LANG.AddToLanguage("English", "totem_other_terrorist", "This is the Totem of another terrorist")
LANG.AddToLanguage("English", "totem_own_totem", "This is your Totem")
LANG.AddToLanguage("English", "totem_teammate_totem", "This is a teammate's Totem")
LANG.AddToLanguage("English", "totem_destroy_totem", "Destroy this Totem with your knife!")
